# Generated by Django 2.2.16 on 2021-08-24 15:04

import apps.vadmin.op_drf.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('questionOrigin', models.CharField(help_text='问题来源', max_length=128, verbose_name='问题来源')),
                ('occurTime', models.DateField(help_text='发生时间', verbose_name='发生时间')),
                ('officeId', models.IntegerField(help_text='科室', verbose_name='科室')),
                ('resPerson', models.CharField(help_text='责任人', max_length=64, verbose_name='责任人')),
                ('followPerson', models.IntegerField(help_text='跟进人', verbose_name='跟进人')),
                ('quesTitle', models.CharField(help_text='问题主题', max_length=128, verbose_name='问题主题')),
                ('quesDescription', models.TextField(help_text='问题描述', verbose_name='问题描述')),
                ('submitter', models.IntegerField(help_text='下单人', verbose_name='下单人')),
                ('fileId', models.IntegerField(blank=True, help_text='文件id', null=True, verbose_name='文件id')),
                ('fileName', models.CharField(blank=True, help_text='文件名称', max_length=128, null=True, verbose_name='文件名称')),
                ('relate', models.CharField(blank=True, help_text='是否涉及其他产品', max_length=128, null=True, verbose_name='是否涉及其他产品')),
                ('causeAnalysis', models.TextField(help_text='原因分析', verbose_name='原因分析')),
                ('tempSolution', models.TextField(help_text='临时解决方案', verbose_name='临时解决方案')),
                ('longSolution', models.TextField(help_text='长期解决方案', verbose_name='长期解决方案')),
                ('alternative', models.TextField(help_text='预防措施', verbose_name='预防措施')),
                ('detailPlan', models.TextField(help_text='详细计划', verbose_name='详细计划')),
                ('status', models.IntegerField(help_text='问题状态', verbose_name='问题状态')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('files', models.ManyToManyField(blank=True, db_constraint=False, help_text='预留多文件上传', null=True, to='system.SaveFile', verbose_name='预留多文件上传')),
            ],
            options={
                'verbose_name': '质量跟进',
                'verbose_name_plural': '质量跟进',
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', apps.vadmin.op_drf.fields.DescriptionField(blank=True, default='', help_text='描述', null=True, verbose_name='描述')),
                ('modifier', apps.vadmin.op_drf.fields.ModifierCharField(blank=True, help_text='该记录最后修改者', max_length=255, null=True, verbose_name='修改者')),
                ('dept_belong_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='数据归属部门')),
                ('update_datetime', apps.vadmin.op_drf.fields.UpdateDateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', apps.vadmin.op_drf.fields.CreateDateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('officeId', models.IntegerField(help_text='分析科室', verbose_name='分析科室')),
                ('userId', models.IntegerField(help_text='用户名', verbose_name='用户名')),
                ('status', models.CharField(help_text='维护状态', max_length=32, verbose_name='维护状态')),
                ('content', models.TextField(help_text='每日答复', verbose_name='每日答复')),
                ('fileId', models.IntegerField(blank=True, help_text='文件id', null=True, verbose_name='文件id')),
                ('fileName', models.CharField(blank=True, help_text='文件名称', max_length=128, null=True, verbose_name='文件名称')),
                ('creator', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('files', models.ManyToManyField(blank=True, help_text='预留多文件上传', null=True, to='system.SaveFile', verbose_name='预留多文件上传')),
                ('questionFollow', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_follow', to='qualityFollow.QuestionFollow', verbose_name='所属跟进问题')),
            ],
            options={
                'verbose_name': '每日维护',
                'verbose_name_plural': '每日维护',
            },
        ),
    ]
